version: "3.3"
services:
  angular:
    build: .
    ports:
      - "4200:4200"
  express:
    build: "NodeReader"
    ports:
      - "3200:3200"
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
