version: "3.3"
services:
  angular:
    build: .
    ports:
      - "4200:4200"
      
  express:
    build: "NodeReader"
    ports:
      - "3200:3200"
  mongo:
      build:         
        context: "./NodeReader/docker/mongo/"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: madmin
        MONGO_INITDB_ROOT_PASSWORD: simple
      volumes: 
        - mongodbdata:/data/db
      expose: 
        - "27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: madmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: simple
    depends_on:
    - mongo
    
volumes: 
  mongodbdata: ~
