version: "3.3"
services:
  angular:
    build: .
    ports:
      - "4200:4200"
  express:
    build: "NodeReader"
    ports:
      - "3200:3200"
  mongo:
      build:         
        context: "./NodeReader/docker/mongo/"
        #dockerfile: ./NodeReader/docker/mongo/Dockerfile
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      volumes: 
        - mongodbdata:/data/db
      expose: 
        - "27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    
volumes: 
  mongodbdata: ~
